config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
    get '/account_update' => 'devise/registrations#edit'
  end

  root 'pages#index'

  resources :items, except: [:show]
  resources :bookings, except: [:edit, :update, :destroy]
  resources :manages do
    member do
      patch :set_close
      patch :set_active
    end
  end

end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  item_id    :integer
#  quantity   :integer
#  startdate  :datetime
#  enddate    :datetime
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Booking < ActiveRecord::Base
  enum status: {"Active" => 0, "Closed" => 1, "Expired" => 2}
  after_initialize :set_default_status, :if => :new_record?
  after_create :subtract_quantity

  validates_presence_of :item_id, :quantity, :startdate, :enddate, :status
  validate :available_quantity

  belongs_to :user
  belongs_to :item

  def is_active?
    status === "Active"
  end

  def is_closed?
    status === "Closed"
  end

  def is_expired?
    status === "Expired"
  end

  def set_default_status
    self.status ||= 0
  end

  def subtract_quantity
    new_quantity = self.item.quantity - self.quantity
    self.item.update_attributes(:quantity => new_quantity)
  end

  def available_quantity
    if self.quantity > self.item.quantity && self.item.quantity != 0
      errors.add(:quantity, ": You can't add more than #{self.item.quantity}")
    elsif self.item.quantity == 0
      errors.add(:quantity, ": Sorry! There is no stock for #{self.item.name}. Please choose another item")
    end
  end

  def overdue
    if self.enddate < Time.now && !self.is_closed?
      self.update(status: 2)
    elsif self.enddate > Time.now && !self.is_closed?
      self.update(status: 0)
    end
  end

  def is_overdue?
    due_date_absolute < Time.now && self.is_expired?
  end

  def due_date_absolute
    self.enddate
  end

  def overdue_rate
    10
  end

  def fine
    overdue_rate * ((Time.now.beginning_of_day - due_date_absolute) / 1.days)
  end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  code       :string(255)
#  quantity   :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Item < ActiveRecord::Base
  enum status: {"Returnable" => 0, "Not Returnable" => 1}
  after_create :random_product_code

  has_many :bookings, dependent: :destroy

  validates_presence_of :name, :quantity, :status

  def is_returnable?
    status === "Returnable"
  end

  def is_not_returnable?
    status === "Not Returnable"
  end

  def random_product_code
    random = ['1'..'9'].map { |i| i.to_a }.flatten
    product_code = (0...7).map { random[rand(random.length)] }.join
    self.update_attributes(:code => product_code)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  role                   :integer
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  status                 :integer
#

class User < ActiveRecord::Base
  enum role: [:user, :admin, :supplier]
  enum status: {"Active" => 0, "Suspend" => 1}
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings

  def set_default_role
    self.role ||= :user
    self.status ||= "Active"
  end

  def is_active?
    status === "Active"
  end

  def is_suspend?
    status === "Suspend"
  end

  def check_status
    self.bookings.pluck(:status).include?(2) ? self.update(status: 1) : self.update(status: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:status, :email, :password, :password_confirmation, :remember_me) }
  end

  def admin_only
    unless current_user.admin?
      redirect_to root_url, :alert => "Only admin can access this page"
    end
  end

  def user_only
    unless current_user.user?
      redirect_to root_url, :alert => "Only user can access this page"
    end
  end

  def active_user_only
    unless current_user.is_active?
      redirect_to bookings_url, :alert => "Sorry! You are not allowed to place any booking at the moment."
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_user, only: [:index, :new, :create, :show]
  before_filter :active_user_only, only: [:new, :create]
  
  def index
    @bookings = Booking.where(user_id: @user)
  end

  def new
    @items = Item.all
    @booking ||= Booking.new
    render
  end

  def create
    @items = Item.all
    @booking = @user.bookings.new(booking_params)
    if @booking.save
      redirect_to bookings_path, notice: "Awesome! New booking has been save!"
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.where(id: params[:id], user: @user).take
    if @booking
      render
    else
      redirect_to bookings_path, notice: "Oopss! Booking not found!"
    end
  end

  private

    def set_user
      @user = current_user
    end

    def booking_params
      params.require(:booking).permit(:item_id, :quantity, :startdate, :enddate)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_item, only: [:edit, :update, :destroy]
  before_filter :admin_only

  def index
    @items = Item.all
  end

  def new
    @item ||= Item.new
    render
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "Awesome! New item has been added to the list"
    else
      render 'new'
    end
  end

  def edit
    if @item
      render
    else
      redirect_to items_path, notice: "Ooppss! Item not found. Sorry!"
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: "Awesome! Item has been updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: "Note! The item has been removed!"
  end

  private

    def set_item
      @item = Item.find_by_id(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :code, :quantity, :status)
    end
end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  before_action :authenticate_user!
  before_filter :admin_only

  def index
    @manages = Booking.all
  end

  def show
    @manage = Booking.find(params[:id])
    if @manage
      render
    else
      redirect_to manages_path, notice: "Oopss! Booking not found!"
    end
  end

  def set_close
    @manage = Booking.find(params[:id])
    @manage.update_attributes(status: 1)
    redirect_to manages_path
  end

  def set_active
    @manage = Booking.find(params[:id])
    @manage.update_attributes(status: 0)
    redirect_to manages_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
  "#{controller_name} #{action_name}"
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "https://gravatar.com/avatar/#{gravatar_id}.png?s=35"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_alert.html.haml
- if alert
  .alert.alert-danger.alert-dismissible.nomar-bot{:role => "alert"}
    %button.close{"data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = alert
- elsif notice
  .alert.alert-warning.alert-dismissible.nomar-bot{:role => "alert"}
    %button.close{"data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = notice

app/views/application/_header.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Researchbods", root_path, class: "navbar-brand"
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "My Booking", bookings_path
        %li= link_to "Manage Items", items_path
        %li= link_to "Manage All Bookings", manages_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            = link_to "", class: "dropdown-toggle", "data-toggle" => "dropdown", role: "button", "aria-expanded" => "false" do
              = image_tag avatar_url(current_user), alt: "#{current_user.email}", class: "img-circle"
              = current_user.email
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li= link_to "Account Settings", account_update_path
              %li.divider 
              %li= link_to "Logout", destroy_user_session_path, method: "delete"
        - else
          = link_to login_path, class: "btn btn-default btn-primary btn-xs navbar-btn" do
            .small.glyphicon.glyphicon-lock
            Sign In
          = link_to register_path, class: "btn btn-default btn-xs navbar-btn" do
            .small.glyphicon.glyphicon-user
            Create An Account
      - if user_signed_in?
        %p.navbar-text.navbar-right.small.hidden-xs{style: "margin-right:20px;"}
          Status:
          - if current_user.is_active?
            %span.label.label-primary= current_user.status
          - elsif current_user.is_suspend?
            %span.label.label-danger= current_user.status

app/views/bookings/_form.html.haml
= form_for @booking, html: { class: "form-horizontal" } do |f|
  .panel-body
    - if @booking.errors.any?
      .alert.alert.danger.alert-dismissable
        %button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
        %strong
          = pluralize(@booking.errors.count, "error")
          prohibited this page from being saved:
        %ul
          - @booking.errors.full_messages.each do |msg|
            %li= msg
    .row
      .col-md-6
        .form-group
          = f.label :item_id, "Item", class: "col-md-2 control-label"
          .col-md-10
            = f.collection_select :item_id, Item.order(:name), :id, :name, {}, :class => "form-control"
        .form-group
          = f.label :quantity, "Quantity", class: "col-md-2 control-label"
          .col-md-10
            = f.text_field :quantity, class: "form-control", placeholder: "10"
        .form-group
          = f.label :startdate, "Start Date", class: "col-md-2 control-label"
          .col-md-10
            = f.text_field :startdate, class: "form-control", value: "#{Time.zone.now.strftime("%d %B %Y at %I:%M %p")}", readonly: true
        .form-group
          = f.label :enddate, "End Date", class: "col-md-2 control-label"
          .col-md-10
            = f.text_field :enddate, class: "form-control", value: "#{2.days.from_now.beginning_of_day.strftime("%d %B %Y at %I:%M %p")}", readonly: true
      .col-md-6
        %pre
          %table.table.table-bordered.table-hovered
            %caption List available item
            %thead
              %tr
                %th Name
                %th Code
                %th Quantity
                %th Status
            %tbody
              - @items.each do |item|
                %tr
                  %td= item.name
                  %td= item.code
                  %td= item.quantity
                  %td= item.status
  .panel-footer
    = f.submit "Submit", class: "btn btn-primary"
    = link_to "Cancel", bookings_path, class: "btn btn-default"

app/views/bookings/index.html.haml
.page-header
  %h1 List of bookings
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Booking List #{link_to_if(!current_user.is_suspend?, "Add new booking", new_booking_url, class: "btn btn-xs btn-primary pull-right", style: "color:#FFFFFF;")}
  .panel-body
    %table.table.table-bordered.table-hovered
      %thead
        %tr
          %th Item
          %th Quantity
          %th Status
          %th.col-md-2 Start Date
          %th.col-md-2 End Date
          %th.col-md-2 Action
          %th Fine
      %tbody
        - @bookings.each do |booking|
          %tr
            %td= booking.item.name
            %td= booking.quantity
            %td
              - if booking.is_active?
                %span.label.label-primary= booking.status
              - elsif booking.is_closed?
                %span.label.label-warning= booking.status
              - else
                %span.label.label-danger= booking.status
            %td= booking.startdate.strftime("%d %B %Y at %I:%M %p")
            %td= booking.enddate.strftime("%d %B %Y at %I:%M %p")
            %td
              = link_to booking_path(booking), class: "btn btn-default btn-block btn-xs" do
                %span.glyphicon.glyphicon-share{"aria-hidden" => true}
            %td
              - if booking.is_overdue? == true
                = number_to_currency(booking.fine)
              - else
                N/A

app/views/bookings/new.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title New booking
  = render 'form'

app/views/bookings/show.html.haml
.page-header
  %h1 Booking Details
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Booking List
  .panel-body
    .row
      .col-md-2
        %strong
          Item
      .col-md-4
        = @booking.item.name
    .row
      .col-md-2
        %strong
          Product Code
      .col-md-4
        = @booking.item.code
    .row
      .col-md-2
        %strong
          Quantity
      .col-md-4
        = @booking.quantity
    .row
      .col-md-2
        %strong
          Status
      .col-md-4
        - if @booking.is_active?
          %span.label.label-primary= @booking.status
        - elsif @booking.is_closed?
          %span.label.label-warning= @booking.status
        - else
          %span.label.label-danger= @booking.status
    .row
      .col-md-2
        %strong
          Start Date
      .col-md-4
        = @booking.startdate.strftime("%d %B %Y at %I:%M %p")
    .row
      .col-md-2
        %strong
          End Date
      .col-md-4
        = @booking.enddate.strftime("%d %B %Y at %I:%M %p")
  .panel-footer
    = link_to "Back", bookings_path, class: "btn btn-default"

app/views/items/_form.html.haml
= form_for @item, html: { class: "form-horizontal" } do |f|
  .panel-body
    - if @item.errors.any?
      .alert.alert.danger.alert-dismissable
        %button.close{type: "button", 'data-dismiss' => 'alert', 'alert-hidden' => 'true'} &times;
        %strong
          = pluralize(@item.errors.count, "error")
          prohibited this page from being saved:
        %ul
          - @item.errors.full_messages.each do |msg|
            %li= msg
    .row
      .col-md-6
        .form-group
          = f.label :name, "Item Name", class: "col-md-2 control-label"
          .col-md-10
            = f.text_field :name, class: "form-control", placeholder: "Pencil"
        .form-group
          = f.label :status, "Status", class: "col-sm-2 control-label"
          .col-sm-10
            = f.select(:status, Item.statuses.keys.map {|status| [status.titleize,status]}, {}, class: "form-control")
        .form-group
          = f.label :quantity, "Quantity", class: "col-sm-2 control-label"
          .col-sm-10
            = f.text_field :quantity, class: "form-control", rows: 5, placeholder: "10"
  .panel-footer
    = f.submit "Submit", class: "btn btn-primary"
    = link_to "Cancel", items_path, class: "btn btn-default"

app/views/items/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Edit item
  = render 'form'

app/views/items/index.html.haml
.page-header
  %h1 List of items
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Item List #{link_to "Add new item", new_item_url, class: "btn btn-xs btn-primary pull-right", style: "color:#FFFFFF;"}
  .panel-body
    %table.table.table-bordered.table-hovered
      %thead
        %tr
          %th Name
          %th Code
          %th Quantity
          %th.col-md-2 Status
          %th.col-md-2 Date Created
          %th.col-md-2 Action
      %tbody
        - @items.each do |item|
          %tr
            %td= item.name
            %td= item.code
            %td= item.quantity
            %td
              - if item.is_returnable?
                %span.label.label-primary= item.status
              - else
                %span.label.label-danger= item.status
            %td= item.created_at.strftime("%d %B %Y")
            %td
              .btn-group.btn-group-justified.btn-group-xs
                = link_to edit_item_url(item), class: "btn btn-default" do
                  %span.glyphicon.glyphicon-edit{"aria-hidden" => true}
                = link_to item_url(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
                  %span.glyphicon.glyphicon-remove{"aria-hidden" => true}

app/views/items/new.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title New item
  = render 'form'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%meta{:charset => "UTF-8"}/
		%title Researchbods
		%meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body{class: "#{body_class}"}
		= render partial: "alert"
		= render partial: "header"
		.container
			- if user_signed_in? && current_user.is_suspend?
				.alert.alert-danger{role: "alert"}
					%strong
						Oh snap!
					Your account has been suspended due to a problem with your previous booking. During this time, you can't place any booking until you resolve the current problem. Thank you!
			= yield

app/views/manages/index.html.haml
.page-header
  %h1 List of all bookings
.panel.panel-default
  .panel-heading
    %h3.panel-title
      All Booking List
  .panel-body
    %table.table.table-bordered.table-hovered
      %thead
        %tr
          %th User
          %th User Status
          %th Item
          %th Quantity
          %th.col-md-1 Status
          %th.col-md-2 Start Date
          %th.col-md-2 End Date
          %th.col-md-2 Action
      %tbody
        - @manages.each do |manage|
          %tr
            %td= manage.user.email
            %td
              - if manage.user.is_active?
                %span.label.label-primary= manage.user.status
              - elsif manage.user.is_suspend?
                %span.label.label-danger= manage.user.status
            %td= manage.item.name
            %td= manage.quantity
            %td
              - if manage.is_active?
                %span.label.label-primary= manage.status
              - elsif manage.is_closed?
                %span.label.label-warning= manage.status
              - else
                %span.label.label-danger= manage.status
            %td= manage.startdate.strftime("%d %B %Y at %I:%M %p")
            %td= manage.enddate.strftime("%d %B %Y at %I:%M %p")
            %td
              .btn-group.btn-group-justified
                = link_to manage_path(manage), class: "btn btn-default btn-xs" do
                  %span.glyphicon.glyphicon-share{"aria-hidden" => true}
                -if manage.is_active? || manage.is_expired?
                  = link_to 'Mark as closed',set_close_manage_path(manage), method: :patch, class: "btn btn-xs btn-warning"
                -if manage.is_closed?
                  = link_to 'Mark as active',set_active_manage_path(manage), method: :patch, class: "btn btn-xs btn-primary"

app/views/manages/show.html.haml
.page-header
  %h1 Booking Details
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Booking List
  .panel-body
    .row
      .col-md-2
        %strong
          User
      .col-md-4
        = @manage.user.email
    .row
      .col-md-2
        %strong
          Item
      .col-md-4
        = @manage.item.name
    .row
      .col-md-2
        %strong
          Quantity
      .col-md-4
        = @manage.quantity
    .row
      .col-md-2
        %strong
          Status
      .col-md-4
        - if @manage.is_active?
          %span.label.label-primary= @manage.status
        - elsif @manage.is_closed?
          %span.label.label-warning= @manage.status
        - else
          %span.label.label-danger= @manage.status
    .row
      .col-md-2
        %strong
          Start Date
      .col-md-4
        = @manage.startdate.strftime("%d %B %Y at %I:%M %p")
    .row
      .col-md-2
        %strong
          End Date
      .col-md-4
        = @manage.enddate.strftime("%d %B %Y at %I:%M %p")
  .panel-footer
    = link_to "Back", manages_path, class: "btn btn-default"

app/views/pages/index.html.haml
%h1 Researchbods
%p You can find more information in the readme file.